// Licensed under the MIT license by loonfactory.

namespace Loonfactory.Google.Apis.YouTube.V3.Watermarks;

/// <summary>
/// Represents a watermark resource.
/// </summary>
public class WatermarkResource
{
    /// <summary>
    /// The timing information for watermark display.
    /// </summary>
    public WatermarkTiming? Timing { get; set; }

    /// <summary>
    /// The position information for watermark display.
    /// </summary>
    public WatermarkPosition? Position { get; set; }

    /// <summary>
    /// The URL of the watermark image generated by YouTube.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// The watermark image bytes.
    /// Serialized as a base64 string in JSON requests.
    /// </summary>
    public byte[]? ImageBytes { get; set; }

    /// <summary>
    /// The channel ID that the watermark image links to.
    /// </summary>
    public string? TargetChannelId { get; set; }
}
